
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CARACTER_ESPECIAL = 19;
  public static final int SRR = 22;
  public static final int LR_CERRADURA_KLEENE = 11;
  public static final int LR_DISYUNCION = 10;
  public static final int FLECHA = 23;
  public static final int LR_LLAVE_IZQ = 8;
  public static final int LR_CERRADURA_INTERROGACION = 13;
  public static final int LR_PUNTO_COMA = 7;
  public static final int LR_LLAVE_DER = 9;
  public static final int LETRA_MINUSCULA = 16;
  public static final int ID = 20;
  public static final int PORCENTAJE = 14;
  public static final int SR = 21;
  public static final int SEPARADOR = 15;
  public static final int PR_CONJ = 2;
  public static final int MAYOR = 3;
  public static final int EOF = 0;
  public static final int LR_COMA = 5;
  public static final int LETRA_MAYUSCULA = 17;
  public static final int NUMERO = 18;
  public static final int error = 1;
  public static final int LR_PUNTO = 6;
  public static final int LR_CERRADURA_POSITIVA = 12;
  public static final int LR_DOS_PUNTOS = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PR_CONJ",
  "MAYOR",
  "LR_DOS_PUNTOS",
  "LR_COMA",
  "LR_PUNTO",
  "LR_PUNTO_COMA",
  "LR_LLAVE_IZQ",
  "LR_LLAVE_DER",
  "LR_DISYUNCION",
  "LR_CERRADURA_KLEENE",
  "LR_CERRADURA_POSITIVA",
  "LR_CERRADURA_INTERROGACION",
  "PORCENTAJE",
  "SEPARADOR",
  "LETRA_MINUSCULA",
  "LETRA_MAYUSCULA",
  "NUMERO",
  "CARACTER_ESPECIAL",
  "ID",
  "SR",
  "SRR",
  "FLECHA"
  };
}

